"""added gamesPlayed

Revision ID: 81e9785382c8
Revises: 856ae4c396ea
Create Date: 2024-02-01 15:45:08.718115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e9785382c8'
down_revision = '856ae4c396ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gamesPlayed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gamesPlayed')

    # ### end Alembic commands ###
